// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID            string
	BalanceMicros int64
}

type Entry struct {
	ID           int64
	AccountID    string
	AmountMicros int64
	CreatedAt    pgtype.Timestamptz
}

type IdempotencyKey struct {
	Key         string
	ErrorCode   string
	ErrorDetail string
	CreatedAt   pgtype.Timestamptz
}
