// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (id, balance_micros)
VALUES ($1, $2)
`

type CreateAccountParams struct {
	ID            string
	BalanceMicros int64
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.Exec(ctx, createAccount, arg.ID, arg.BalanceMicros)
	return err
}

const getAccountForUpdate = `-- name: GetAccountForUpdate :one
SELECT id, balance_micros FROM accounts WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetAccountForUpdate(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountForUpdate, id)
	var i Account
	err := row.Scan(&i.ID, &i.BalanceMicros)
	return i, err
}

const getBalance = `-- name: GetBalance :one
SELECT balance_micros FROM accounts WHERE id = $1
`

func (q *Queries) GetBalance(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRow(ctx, getBalance, id)
	var balance_micros int64
	err := row.Scan(&balance_micros)
	return balance_micros, err
}

const insertEntry = `-- name: InsertEntry :one
INSERT INTO entries (account_id, amount_micros)
VALUES ($1, $2)
RETURNING id
`

type InsertEntryParams struct {
	AccountID    string
	AmountMicros int64
}

func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertEntry, arg.AccountID, arg.AmountMicros)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateBalance = `-- name: UpdateBalance :exec
UPDATE accounts SET balance_micros = $2 WHERE id = $1
`

type UpdateBalanceParams struct {
	ID            string
	BalanceMicros int64
}

func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) error {
	_, err := q.db.Exec(ctx, updateBalance, arg.ID, arg.BalanceMicros)
	return err
}
